name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: [ bmw-custom-ubuntu-24.04-medium ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for better relevancy of analysis

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests with coverage
        run: mvn -B verify --no-transfer-progress

      - uses: ATC-Marketplace/sonarqube-scan@v3.1.0
        with:
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_properties: "-Dsonar.projectKey=tnrcore_tnrarch-archi-graph-j -Dsonar.java.sources=src/main/java -Dsonar.sources=src/main"
